uvmf:
  environments:
    "lc3" :
      subenvs :
        - name: "fetch_env"
          type: "fetch"
        - name: "decode_env"
          type: "decode"
        - name: "execute_env"
          type: "execute"
        - name: "writeback_env"
          type: "writeback"
        - name: "memaccess_env"
          type: "memaccess"
        - name: "controller_env"
          type: "controller"
      agents :
        - name: "instr_mem_agent" 
          type: "imem"
          initiator_responder: "RESPONDER"
        - name: "dat_mem_agent" 
          type: "data_mem"
          initiator_responder: "RESPONDER"
      analysis_components:
      - name: imem_cov
        parameters: []
        type: imem_coverage
      - name: dmem_cov
        parameters: []
        type: dmem_coverage
      tlm_connections:
      - driver: instr_mem_agent.monitored_ap
        receiver: imem_cov.imem_cov_ae
      - driver: dat_mem_agent.monitored_ap
        receiver: dmem_cov.dmem_cov_ae
      register_model:
        use_adapter: "False"
        use_explicit_prediction: "False"
